/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listChurches"];
        put?: never;
        post: operations["createChurch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        get: operations["getChurch"];
        put: operations["updateChurch"];
        post?: never;
        delete: operations["archiveChurch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        get: operations["listGroups"];
        put?: never;
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get: operations["getGroup"];
        put: operations["updateGroup"];
        post?: never;
        delete: operations["archiveGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/groups/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        /** @description CSV of all active groups, top-level groups before their subgroups. ParentName is the parent's Name, blank for top-level groups. */
        get: operations["exportGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/groups/import-template": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        /** @description CSV header row only. */
        get: operations["groupImportTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/groups/import": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Best-effort bulk create/update, up to 500 rows per call. A row with a matching Id updates that group; otherwise a group is created. ParentName must reference an active top-level group's Name; a parent row must appear before its children's rows in the same call. Errors are reported per row without aborting the batch. */
        post: operations["importGroups"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post: operations["createMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get: operations["getMember"];
        put: operations["updateMember"];
        post?: never;
        delete: operations["archiveMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/members/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        /** @description CSV of all active members. ScanCode is not included. Groups are colon-separated group names ("Parent / Child" for subgroups). Custom field columns use the field name. */
        get: operations["exportMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/members/import-template": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        /** @description CSV header row only, matching the export schema for this church's active custom fields. */
        get: operations["memberImportTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/members/import": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Best-effort bulk create/update, up to 500 rows per call. A row with a matching Id updates that member; otherwise a member is created. Errors are reported per row without aborting the batch. */
        post: operations["importMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/custom-fields": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        get: operations["listCustomFields"];
        put?: never;
        post: operations["createCustomField"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/custom-fields/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get: operations["getCustomField"];
        put: operations["updateCustomField"];
        post?: never;
        delete: operations["archiveCustomField"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get: operations["getEvent"];
        put: operations["updateEvent"];
        post?: never;
        delete: operations["archiveEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/events/{id}/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get: operations["listEventOccurrences"];
        put?: never;
        /** @description Creates the next missing upcoming occurrence. Existing overrides and cancellations are never overwritten. */
        post: operations["generateOccurrences"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/events/{id}/occurrence-check-in-counts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        /** @description Active check-in totals for this event, grouped by occurrence. Occurrences absent from the response have zero active check-ins. */
        get: operations["getOccurrenceCheckInCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        get: operations["discoverOccurrences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/occurrences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get: operations["getOccurrence"];
        put: operations["overrideOccurrence"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/occurrences/{id}/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Explicit memberId is not proof of identity. Check-in is allowed regardless of occurrence start/end times. Cancelled or archived occurrences reject new check-ins. Repeated requests return the existing receipt. */
        post: operations["checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/occurrences/{id}/check-ins/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
                memberId: string;
            };
            cookie?: never;
        };
        get: operations["checkInStatus"];
        put?: never;
        post?: never;
        /** @description Marks an active check-in as undone while retaining its audit history. Repeated calls are idempotent. */
        delete: operations["undoCheckIn"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/occurrences/{id}/scan-check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resolve a current church-scoped code and check in without a time restriction. Codes are identifiers, not authentication. Cosmos requires strong consistency. 404 for unknown/replaced codes; 409 for new attendance at cancelled/archived resources; 429 includes Retry-After. Already-persisted receipts return 200. */
        post: operations["scanCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/occurrences/{id}/scan-check-ins/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Read-only status recovery. Code is in the body to avoid URL logging. Replaced codes return 404, which does not prove that an earlier write failed. */
        post: operations["scanCheckInStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/churches/{churchId}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        /** @description Ranges are [from,to), maximum 93 days when supplied. Reports include active check-ins only. Group filters use check-in-time snapshots, not current memberships. */
        get: operations["reportAttendance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ScanMember: {
            id: string;
            firstName: string;
            lastName: string;
        };
        Document: {
            readonly id: string;
            readonly churchId: string;
            readonly kind: string;
            readonly _etag: string;
            readonly active: boolean;
            readonly searchText?: string;
        } & {
            [key: string]: unknown;
        };
        ChurchInput: {
            name: string;
            /**
             * @description Whether member card and scan check-in functionality is available.
             * @default true
             */
            scanCodesEnabled: boolean;
            /**
             * @description Preferred format for member cards and scan check-in. Existing churches default to QR.
             * @default qr
             * @enum {string|null}
             */
            scanCodeFormat: "qr" | "code128" | null;
        };
        GroupInput: {
            name: string;
            parentGroupId?: string | null;
        };
        GuardianInput: {
            firstName: string;
            middleName?: string | null;
            lastName: string;
            /** @enum {string} */
            relationship: "Mother" | "Father" | "Grandmother" | "Grandfather" | "Others";
            /** @description Required when relationship is Others. */
            otherRelationship?: string | null;
            phone: string;
            /** Format: email */
            email: string;
        };
        MemberInput: {
            /**
             * @description Children require guardian1; adults cannot have school or guardian information.
             * @enum {string}
             */
            memberType: "child" | "adult";
            allergyDetail?: string | null;
            /** @description Current church-unique code. Canonical 8-64 uppercase ASCII letters/digits/hyphens. Omission on update preserves the assignment; null removes it. Replacement deletes the old lookup without archiving. Conflict returns 409. */
            scanCode?: string | null;
            /**
             * @description Card presentation; default qr when a code is assigned. Omission preserves current format.
             * @enum {string|null}
             */
            scanCodeFormat?: "qr" | "code128" | null;
            firstName: string;
            lastName: string;
            middleName?: string | null;
            /** Format: date */
            birthDate?: string | null;
            /** @description Child members only. */
            school?: string | null;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            /** @description Required for child members; forbidden for adults. */
            guardian1?: components["schemas"]["GuardianInput"];
            /** @description Optional for child members; forbidden for adults. */
            guardian2?: components["schemas"]["GuardianInput"];
            groupIds?: string[];
            /** @description Keys are custom-field definition IDs; values must match each definition's type. */
            customFields?: {
                [key: string]: unknown;
            };
        };
        CustomFieldInput: {
            name: string;
            /** @enum {string} */
            fieldType: "text" | "number" | "boolean" | "date";
        };
        EventInput: {
            name: string;
            /**
             * @description Wall-clock datetime without Z/offset.
             * @example 2026-09-20T09:00:00
             */
            localStart: string;
            /** @example America/New_York */
            timeZone: string;
            durationMinutes: number;
            /**
             * @description Daily/weekly/monthly/yearly RRULE. No sub-day modifiers.
             * @example FREQ=WEEKLY;BYDAY=SU
             */
            recurrenceRule?: string | null;
            /** @description Default check-in groups. Empty means all church members. */
            groupIds?: string[];
        };
        OccurrenceOverride: {
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            cancelled: boolean;
            /** @description A reversible organizational state permitted only after the occurrence ends. */
            archived: boolean;
            /** @description Omit to preserve the current filter; empty clears the filter. */
            groupIds?: string[] | null;
        };
        OccurrenceCheckInCount: {
            occurrenceId: string;
            checkedInCount: number;
        };
        /** @description Blank Id creates a member; an Id matching an existing member updates it, otherwise a member is created with that Id. */
        MemberImportRow: {
            id?: string | null;
            /** @enum {string|null} */
            memberType?: "child" | "adult" | null;
            firstName?: string | null;
            middleName?: string | null;
            lastName?: string | null;
            /** Format: date */
            birthDate?: string | null;
            school?: string | null;
            phone?: string | null;
            email?: string | null;
            allergyDetail?: string | null;
            /** @description Colon-separated active group names, e.g. Youth:Choir. Subgroups use "Parent / Child". */
            groups?: string | null;
            guardian1FirstName?: string | null;
            guardian1MiddleName?: string | null;
            guardian1LastName?: string | null;
            guardian1Relationship?: string | null;
            guardian1OtherRelationship?: string | null;
            guardian1Phone?: string | null;
            guardian1Email?: string | null;
            guardian2FirstName?: string | null;
            guardian2MiddleName?: string | null;
            guardian2LastName?: string | null;
            guardian2Relationship?: string | null;
            guardian2OtherRelationship?: string | null;
            guardian2Phone?: string | null;
            guardian2Email?: string | null;
            /** @description Keys are active custom-field names for this church. */
            customFields?: {
                [key: string]: string;
            } | null;
        };
        MemberImportRowResult: {
            /** @description 1-based row number, header excluded. */
            row: number;
            id?: string | null;
            /** @enum {string} */
            action: "created" | "updated" | "error";
            errors?: string[] | null;
        };
        MemberImportResult: {
            created: number;
            updated: number;
            failed: number;
            results: components["schemas"]["MemberImportRowResult"][];
        };
        /** @description Blank Id creates a group; an Id matching an existing group updates it, otherwise a group is created with that Id. */
        GroupImportRow: {
            id?: string | null;
            name?: string | null;
            /** @description Name of an active top-level group. Blank means this row is itself a top-level group. A parent row must appear before its children's rows in the same import call. */
            parentName?: string | null;
        };
        GroupImportRowResult: {
            /** @description 1-based row number, header excluded. */
            row: number;
            id?: string | null;
            /** @enum {string} */
            action: "created" | "updated" | "error";
            errors?: string[] | null;
        };
        GroupImportResult: {
            created: number;
            updated: number;
            failed: number;
            results: components["schemas"]["GroupImportRowResult"][];
        };
    };
    responses: {
        /** @description Confirmed attendance and minimal member identity */
        ScanResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    member: components["schemas"]["ScanMember"];
                    receipt: components["schemas"]["Document"];
                    already: boolean;
                };
            };
        };
        /** @description Persisted document */
        Created: {
            headers: {
                ETag?: string;
                Location?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Document"];
            };
        };
        /** @description Resource with type-specific fields and server metadata */
        Document: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Document"];
            };
        };
        /** @description Page sorted by ID */
        Page: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    items: components["schemas"]["Document"][];
                    continuationToken: string | null;
                };
            };
        };
        /** @description Problem Details: 400 invalid input, 404 not found, 405 unsupported method, 409 conflict/cancelled occurrence, 412 stale ETag, 413 body too large, 415 unsupported content type, 428 missing ETag, 429 throttled, 503 unavailable. Retry 429/503 check-ins with the same IDs. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    type?: string;
                    title?: string;
                    status?: number;
                    detail?: string;
                    traceId?: string;
                };
            };
        };
    };
    parameters: {
        churchId: string;
        id: string;
        /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
        IfMatch: string;
        /** @description Case-insensitive name substring. */
        search: string;
        pageSize: number;
        /** @description Opaque, URL-encoded token bound to the same filters and page size. Continue until null, including after empty Cosmos pages. */
        continuationToken: string;
        includeArchived: boolean;
        includeSubgroups: boolean;
        eventId: string;
        occurrenceId: string;
        memberId: string;
        groupId: string;
        parentGroupId: string;
        from: string;
        to: string;
    };
    requestBodies: {
        Scan: {
            content: {
                "application/json": {
                    /** @description Trim surrounding whitespace, normalize ASCII uppercase, then require 8-64 letters, digits or hyphens. Preserve leading zeroes. */
                    scanCode: string;
                };
            };
        };
        Church: {
            content: {
                "application/json": components["schemas"]["ChurchInput"];
            };
        };
        Group: {
            content: {
                "application/json": components["schemas"]["GroupInput"];
            };
        };
        Member: {
            content: {
                "application/json": components["schemas"]["MemberInput"];
            };
        };
        CustomField: {
            content: {
                "application/json": components["schemas"]["CustomFieldInput"];
            };
        };
        Event: {
            content: {
                "application/json": components["schemas"]["EventInput"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process healthy, not a database readiness probe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    openapi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This specification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listChurches: {
        parameters: {
            query?: {
                /** @description Case-insensitive name substring. */
                search?: components["parameters"]["search"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description Opaque, URL-encoded token bound to the same filters and page size. Continue until null, including after empty Cosmos pages. */
                continuationToken?: components["parameters"]["continuationToken"];
                includeArchived?: components["parameters"]["includeArchived"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
            default: components["responses"]["Problem"];
        };
    };
    createChurch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Church"];
        responses: {
            201: components["responses"]["Created"];
            default: components["responses"]["Problem"];
        };
    };
    getChurch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    updateChurch: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Church"];
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    archiveChurch: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived; all history retained */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listGroups: {
        parameters: {
            query?: {
                /** @description Case-insensitive name substring. */
                search?: components["parameters"]["search"];
                parentGroupId?: components["parameters"]["parentGroupId"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description Opaque, URL-encoded token bound to the same filters and page size. Continue until null, including after empty Cosmos pages. */
                continuationToken?: components["parameters"]["continuationToken"];
                includeArchived?: components["parameters"]["includeArchived"];
            };
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
            default: components["responses"]["Problem"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Group"];
        responses: {
            201: components["responses"]["Created"];
            default: components["responses"]["Problem"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Group"];
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    archiveGroup: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived; memberships retained; archive children first */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    exportGroups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    groupImportTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    importGroups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rows: components["schemas"]["GroupImportRow"][];
                };
            };
        };
        responses: {
            /** @description Import summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupImportResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listMembers: {
        parameters: {
            query?: {
                /** @description Case-insensitive name substring. */
                search?: components["parameters"]["search"];
                groupId?: components["parameters"]["groupId"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description Opaque, URL-encoded token bound to the same filters and page size. Continue until null, including after empty Cosmos pages. */
                continuationToken?: components["parameters"]["continuationToken"];
                includeArchived?: components["parameters"]["includeArchived"];
            };
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
            default: components["responses"]["Problem"];
        };
    };
    createMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Member"];
        responses: {
            201: components["responses"]["Created"];
            default: components["responses"]["Problem"];
        };
    };
    getMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Member"];
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    archiveMember: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived; attendance retained */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    exportMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    memberImportTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    importMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rows: components["schemas"]["MemberImportRow"][];
                };
            };
        };
        responses: {
            /** @description Import summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberImportResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listCustomFields: {
        parameters: {
            query?: {
                /** @description Case-insensitive name substring. */
                search?: components["parameters"]["search"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description Opaque, URL-encoded token bound to the same filters and page size. Continue until null, including after empty Cosmos pages. */
                continuationToken?: components["parameters"]["continuationToken"];
                includeArchived?: components["parameters"]["includeArchived"];
            };
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
            default: components["responses"]["Problem"];
        };
    };
    createCustomField: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CustomField"];
        responses: {
            201: components["responses"]["Created"];
            default: components["responses"]["Problem"];
        };
    };
    getCustomField: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    updateCustomField: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CustomField"];
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    archiveCustomField: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Definition archived; existing member values retained */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description Case-insensitive name substring. */
                search?: components["parameters"]["search"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description Opaque, URL-encoded token bound to the same filters and page size. Continue until null, including after empty Cosmos pages. */
                continuationToken?: components["parameters"]["continuationToken"];
                includeArchived?: components["parameters"]["includeArchived"];
            };
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
            default: components["responses"]["Problem"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Event"];
        responses: {
            201: components["responses"]["Created"];
            default: components["responses"]["Problem"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Event"];
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    archiveEvent: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived; new check-ins disallowed and history retained */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listEventOccurrences: {
        parameters: {
            query?: {
                from?: components["parameters"]["from"];
                to?: components["parameters"]["to"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description Opaque, URL-encoded token bound to the same filters and page size. Continue until null, including after empty Cosmos pages. */
                continuationToken?: components["parameters"]["continuationToken"];
            };
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
            default: components["responses"]["Problem"];
        };
    };
    generateOccurrences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created occurrence, or null when no upcoming occurrence is missing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        occurrence: components["schemas"]["Document"] | null;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getOccurrenceCheckInCounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active check-in counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OccurrenceCheckInCount"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    discoverOccurrences: {
        parameters: {
            query?: {
                eventId?: components["parameters"]["eventId"];
                from?: components["parameters"]["from"];
                to?: components["parameters"]["to"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description Opaque, URL-encoded token bound to the same filters and page size. Continue until null, including after empty Cosmos pages. */
                continuationToken?: components["parameters"]["continuationToken"];
            };
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
            default: components["responses"]["Problem"];
        };
    };
    getOccurrence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    overrideOccurrence: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact _etag from the last read; missing returns 428 and stale returns 412. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OccurrenceOverride"];
            };
        };
        responses: {
            200: components["responses"]["Document"];
            default: components["responses"]["Problem"];
        };
    };
    checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    memberId: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Document"];
            201: components["responses"]["Created"];
            default: components["responses"]["Problem"];
        };
    };
    checkInStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Check-in status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        checkedIn?: boolean;
                        receipt?: Record<string, never> | null;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    undoCheckIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Undo result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        receipt: components["schemas"]["Document"];
                        undone: boolean;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    scanCheckIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Scan"];
        responses: {
            200: components["responses"]["ScanResult"];
            201: components["responses"]["ScanResult"];
            default: components["responses"]["Problem"];
        };
    };
    scanCheckInStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Scan"];
        responses: {
            /** @description Resolved member and current attendance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        member: components["schemas"]["ScanMember"];
                        checkedIn: boolean;
                        receipt: {
                            [key: string]: unknown;
                        } | null;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    reportAttendance: {
        parameters: {
            query?: {
                /** @description Case-insensitive name substring. */
                search?: components["parameters"]["search"];
                eventId?: components["parameters"]["eventId"];
                occurrenceId?: components["parameters"]["occurrenceId"];
                memberId?: components["parameters"]["memberId"];
                groupId?: components["parameters"]["groupId"];
                includeSubgroups?: components["parameters"]["includeSubgroups"];
                from?: components["parameters"]["from"];
                to?: components["parameters"]["to"];
                pageSize?: components["parameters"]["pageSize"];
                /** @description Opaque, URL-encoded token bound to the same filters and page size. Continue until null, including after empty Cosmos pages. */
                continuationToken?: components["parameters"]["continuationToken"];
            };
            header?: never;
            path: {
                churchId: components["parameters"]["churchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Page"];
            default: components["responses"]["Problem"];
        };
    };
}
